DROP TABLE IF EXISTS connections;
DROP TABLE IF EXISTS pins;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS board_members;
DROP TABLE IF EXISTS boards;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS users;
